### ISSUE TITLE
Issue when quitting games - softlock

### ISSUE THREAD

**Issue by TAGE7** [dimok789/mocha#1]
Hello

When using this + CBHC on sysnand there is a nasty bug that quitting any application causes the Wii U to lock up after being sent back to CBHC. 

It doesn't happen when using a rednand setup or without mocha so this leads us to believe its a mocha specific issue upon reboot.

**Comment by dimok789** [comment]
Did you enable the option for the syshax.xml when launching Mocha?

**Comment by TAGE7** [comment]
Is this the new feature for mocha release 2? this was just released a few minutes ago no?

"added new feature which allows you to disable os full relaunch (only possible in combination with sysNAND, not redNAND)"

Let me retry this

**Comment by TAGE7** [comment]
Fixed by using the feature enabled above.
No editing to anything needed.

**Comment by dimok789** [comment]
It was actually available in version 0.1 too. Nice that you got it fixed.
